version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  sync_test:
    executor:
      name: win/default # executor type
      size: "medium" # resource class, can be "medium", "large", "xlarge", "2xlarge", defaults to "medium" if not specified
      shell: bash.exe
    shell: powershell.exe
    steps:
      - run:
          name: checkout node-tests repo
          command: checkout
      - run: systeminfo
      - run:
          echo "this is the build job"
      - run:
          name: install python dependencies
          command: |
            pip install requests
            pip install psutil
            pip install sqlite-utils>=2.18
            sqlite-utils --version
            pip install pandas
      - store_artifacts:
          path: cardano-node-tests/logfile.log
          destination: node_logs

workflows:
  main:
    jobs:
      - sync_test
