version: 2.1

orbs:
  win: circleci/windows@2.2.0

executors:
  linux:
    machine:
      image: ubuntu-2004:202010-01
#    resource_class: xlarge
  macos:
    macos:
      xcode: 11.3.0
#      resource_class: large
#  windows:
#    executor:
#      name: win/default
#    size: "xlarge" # resource class, can be "medium", "large", "xlarge", "2xlarge", defaults to "medium" if not specified
#    shell: bash.exe

jobs:
  sync_test:
    parameters:
      os:
        type: executor
      env:
        type: string
    executor: << parameters.os >>
    steps:
      - checkout
      - run:
          echo "this is the build job"
      - run:
          name: install python dependencies
          command: |
            pip install requests
            pip install psutil
            pip install sqlite-utils>=2.18
            sqlite-utils --version
      - run:
          name: run sync test
          no_output_timeout: 660m
          env: << parameters.env >>
          command: |
            echo env
            echo $PWD
            ls -d */
            python /c/Users/circleci/project/sync_tests/sync_test2.py -t1 "1.26.1" -e env
      - store_artifacts:
          path: /c/Users/circleci/project/sync_tests/logfile.log
          destination: node_logs

workflows:
  all-tests:
    jobs:
      - sync_test
          matrix:
            parameters:
              os: [ macos, linux ]
              env: [shelley_qa, testnet, staging, mainnet]
#          post-steps: # steps to run after steps defined in the job bar
#            - run:
#                command: echo "upload artifact to s3"
