version: 2.1

orbs:
  win: circleci/windows@2.2.0

parameters:
  tag_no1:
    type: string
    default: "1.26.1"
  tag_no2:
    type: string
    default: None

executors:
  linux:
    machine:
      image: ubuntu-2004:202010-01
#    resource_class: xlarge
  macos:
    macos:
      xcode: 11.3.0
#      resource_class: large
  windows:
    name: win/default
    shell: bash.exe
#    size: "xlarge" # resource class, can be "medium", "large", "xlarge", "2xlarge", defaults to "medium" if not specified

jobs:
  sync_test:
    parameters:
      os:
        type: string
      env:
        type: string
    executor: << parameters.os >>
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          echo "this is the build job"
      - run:
          name: install python dependencies
          command: |
            pip install requests
            pip install psutil
            pip install sqlite-utils>=2.18
            sqlite-utils --version
      - run:
          name: run sync test
          no_output_timeout: 120m
          env: << parameters.env >>
          command: |
            echo $env
            echo $PWD
            echo $HOME
            echo $working_directory
            ls -d */
            python ./sync_tests/sync_test2.py -t1 << pipeline.parameters.tag_no1 >> -t2 << pipeline.parameters.tag_no2 >> -e env
      - store_artifacts:
          path: ./sync_tests/logfile.log
          destination: node_logs

workflows:
  build:
    jobs:
      - sync_test:
          matrix:
            parameters:
              os: [ linux, macos, windows ]
              env: [shelley_qa, testnet, staging, mainnet]
          name: test-on-<< matrix.os >>-with-env-<< matrix.env >>
#          post-steps: # steps to run after steps defined in the job bar
#            - run:
#                command: echo "upload artifact to s3"
